name: Test and Report 

on:
  push:
    branches:
      - main

permissions:
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-versioin: '17'
      
      - name: Install dependencies
        run: | 
          cd javascript
          npm install
        
      - name: Run tests
        id: run-tests
        run: |
          cd javascript
          npm test

      - name: Create issue on test failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "Test Failure: Please fix the bug"
          content-filepath: .github/ISSUE_TEMPLATE/test-failure.md
          labels: bug, "good first issue", "help wanted", "sandbox toy issue"